language: python
python: 2.7

install:
  - pip install -r requirements.txt
  - python setup.py build
  - python setup.py install --bash-completion-dir=/tmp --zsh-completion-dir=/tmp

# command to run tests
script: nosetests
