language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

install:
  - pip install -r requirements.txt
  - python setup.py build
  - python setup.py install --bash-completion-dir=/tmp --zsh-completion-dir=/tmp

# command to run tests
script: nosetests
